### ISSUE TITLE
gpg command does not work but works on debian11 installations

### ISSUE THREAD

**Issue by staticdev** [cisagov/docker-debian11-ansible#1]
# 🐛 Summary #

What's wrong? Please be specific.

## To reproduce ##

Open terminal, type: gpg

## Expected behavior ##

See command output.

## Any helpful log output or screenshots ##

-

Add any screenshots of the problem here.

**Comment by mcdonnnj** [comment]
@staticdev Thanks for your interest in this Docker image. This image is designed to be an Ansible-enabled Docker image commonly used for testing with tools such as [molecule](https://github.com/ansible-community/molecule). As such it is designed to have a minimal initial size which is achieved by only installing the packages necessary to have a functional Ansible installation. Any additional packages should be installed as part of Ansible tasks or independently if using the image interactively.

Please see the [Debian base system page](https://www.debian.org/doc/debian-policy/ch-binary.html#base-system) for more information about what packages you can reasonably expect to be present on a Debian instance/image.
